Update to NixOS 19.09
Let's see how it goes.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -45,17 +45,20 @@ working_directory=$(mktemp -d)
 set +e
   arch=$(uname -a | grep -o "x86_64" | head -n1)
 set -e
-[ ! "$arch" = "x86_64" ] && arch=i686
+if [ ! "$arch" = "x86_64" ]; then
+  log "Sorry, only x86_64 is supported because I couldn't be bothered to check the checksum per arch." >&2
+  exit 1
+fi
 
-primary_version=16.09
-secondary_version=680.4e14fd5
+primary_version=19.09
+secondary_version=2350.d011e474945
 full_version=$primary_version.$secondary_version
 minimal_iso=nixos-minimal-$full_version-${arch}-linux.iso
 graphical_iso=nixos-graphical-$full_version-${arch}-linux.iso
 iso=$minimal_iso
-minimal_checksum=8700fd1861e83dba0c3c2cb348099d2499b2c52844d1771f1aacbf7458990bc8
-graphical_checksum=f1144de2645b1d099035416cb335e33cb56fdf71c8f8900c75a6a91ac2f49464
-checksum=$minimal_checksum
+minimal_checksum_64bit=8116c88094426a219ad34bf86bc5e014875de93e785a2032018810086e55d31b
+graphical_checksum=322a2a6bb45ca978485cf0a263c413af2e6579df4a40bb384b5a4b4e38c12715
+checksum=$minimal_checksum_64bit
 
 minimal_space=3
 graphical_space=5
